apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-tpl4
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0021-tenant/tkrw-pr712-0075-0021-app/devfile-sample-tpl4@sha256:437138f01175b3396c1ed1e575f4a861037e5e89c64aab3c1ddc437a40974d63
        name: my-nodejs
        resources: {}
status: {}
